// Auto-generated from PORTAFOLIO FORMULAS HUSJ.xlsx (sheet: NUTRICIÓN FÓRMULAS E INSUMOS)
window.FORMULAS = [
  {
    "id": "jevity-2-abbott",
    "tipo": "POLIMÉRICAS",
    "laboratorio": "ABBOTT",
    "nombre": "Jevity 2",
    "presentacion": "LPC 500 cc",
    "descripcion_corta": "Fórmula polimérica con fibra",
    "densidad_kcal_ml": 1.05,
    "osmolaridad": 249.0,
    "pct_proteina": 15.22,
    "pct_chos": 53.46,
    "pct_grasas": 29.24,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 20.0,
    "chos_g_por_volumen": 70.0,
    "grasa_g_por_volumen": 17.0,
    "fibra_g_por_volumen": 5.3,
    "grupo_etareo": "ADOLESCENTES Y ADULTOS",
    "nota": "Apme  polimérico, isoosmolar, a base de maltodextrina, caseinatos y mezcla de fibras y fos, para administración por sonda o gastrostomía, desnutrición proteicocalórica moderada asociada a: cirugía de cabeza y cuello, trauma craneoencefálico, acv, miastenia gravis, esclerosis lateral amiotrófica, atrofia muscular espinal, guillain-barré, síndrome de intestino corto, enfermedad del sistema nervioso que presenten un grado de conciencia mínimo; adolescentes y adultos que tienen indicada la vía enteral por sonda como única vía de alimentación, y que no logran suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "fresubin-original-fresenius-kabi",
    "tipo": "POLIMÉRICAS",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Fresubin original",
    "presentacion": "Easy bag 500 cc",
    "descripcion_corta": "Fórmula polimérica sin lactosa",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 220.0,
    "pct_proteina": 15.0,
    "pct_chos": 55.0,
    "pct_grasas": 30.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 19.0,
    "chos_g_por_volumen": 69.0,
    "grasa_g_por_volumen": 17.0,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "A PARTIR DE 3 AÑOS DE EDAD",
    "nota": "Apme formula polimerica, para alimentación por sonda, normal en calorías (1 kcal/ml). A base de maltodextrina, lípidos, proteína láctea (caseína), con vitaminas y minerales. Con epa y dha provenientes de aceite de pescado. Anorexia, enfermedad neurológica, que le impidan suplir sus requerimientos nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "nutrison-1-0-kcal-nutricia",
    "tipo": "POLIMÉRICAS",
    "laboratorio": "NUTRICIA",
    "nombre": "Nutrison 1,0 kcal",
    "presentacion": "Botella optri 1000 cc",
    "descripcion_corta": "Fórmula polimérica normocalórica normoproteica",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 255.0,
    "pct_proteina": 16.1,
    "pct_chos": 49.0,
    "pct_grasas": 34.9,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 20.0,
    "chos_g_por_volumen": 61.5,
    "grasa_g_por_volumen": 19.5,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "PARA NIÑOS A PARTIR DE 6 AÑOS, ADULTOS Y ADULTOS MAYORES",
    "nota": "Apme fórmula polimérica, isotónica, líquida, lista para usar, sin lactosa, con proteínas (de suero, caseína, soya, arveja), carbohidratos, grasas, triglicéridos de cadena media -tcm, ácidos grasos poliinsaturados esencialesepufas (dha, epa y ácido araquidónico), vitaminas, minerales, oligoelementos y carotenoides. Para el manejo nutricional enteral por sonda o acceso enteral a mediano y largo plazo, que presentan desnutrición proteico-calórica moderada o severa asociada a accidente cerebrovascular, neoplasias malignas en estadio iii y iv, sida, caquexia, estado pre y posoperatorio, insuficiencia hepática crónica, que requieren soporte nutricional porque no pueden suplir los requerimientos nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "fresubin-hp-energy-fresenius-kabi",
    "tipo": "POLIMÉRICAS",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Fresubin HP Energy",
    "presentacion": "Easy bag 500/ 1000 cc",
    "descripcion_corta": "Fórmula polimérica baja en carbohidratos, hiperproteica de alta densidad calórica",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 300.0,
    "pct_proteina": 20.0,
    "pct_chos": 45.0,
    "pct_grasas": 35.0,
    "volumen_base_ml": 1000.0,
    "kcal_por_volumen": 1500.0,
    "prote_g_por_volumen": 75.0,
    "chos_g_por_volumen": 170.0,
    "grasa_g_por_volumen": 58.0,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "Adultos",
    "nota": "Para el manejo nutricional de adultos con caquexia o desnutrición proteico calórica moderada o severa, asociadas a: Insuficiencia cardíaca congestiva, enfermedades neurológicas (demencia, secuelas ACV, parkinson, alzheimer), cáncer en estadios III y IV (cabeza y cuello, mama, cuello uterino, páncreas, pulmón, colon, próstata en estadios III y IV), quemaduras de II y III grado, úlceras por presión grado II - IV, adultos con sarcopenia secundaria asociada a: VIH/SIDA enfermedades neurológicas (demencia, secuelas ACV, parkinson, alzheimer), insuficiencia cardiaca congestiva, EPOC, cáncer en estadios III y IV (cabeza y cuello, mama, cuello uterino, páncreas, colon, próstata) con requerimientos nutricionales incrementados de energía y proteínas e incapacidad para suplir sus requerimientos con una alimentación normal o modificada."
  },
  {
    "id": "ensure-plus-hn-abbott",
    "tipo": "POLIMÉRICAS",
    "laboratorio": "ABBOTT",
    "nombre": "Ensure plus HN",
    "presentacion": "LPC 1000 cc",
    "descripcion_corta": "Fórmula polimérica hiperproteica de alta densidad",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 400.0,
    "pct_proteina": 16.7,
    "pct_chos": 54.3,
    "pct_grasas": 29.0,
    "volumen_base_ml": 1000.0,
    "kcal_por_volumen": 1500.0,
    "prote_g_por_volumen": 62.7,
    "chos_g_por_volumen": 203.6,
    "grasa_g_por_volumen": 49.0,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "Adultos",
    "nota": "Apme, polimérico, hipercalórico, a base de maltodextrina, para adultos que presenten desnutrición proteicocalórica de grado moderado/severo, con desnutrición proteico calórica asociada a: enfermedad oncológica en todos los estadios, sida, insuficiencia cardíaca congestiva, enfermedades neurológicas (ela, demencia, lesión postraumática cráneo-encefálica, lesión axonal, secuelas de acv), que requieren de soporte nutricional porque no logran suplir sus requerimientos nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "ensure-clinical-abbott",
    "tipo": "POLIMÉRICAS",
    "laboratorio": "ABBOTT",
    "nombre": "Ensure clinical",
    "presentacion": "LPC 1000 cc",
    "descripcion_corta": "Fórmula polimérica hiperproteica con HMB y FOS, alta densidad calórica",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 382.0,
    "pct_proteina": 21.45,
    "pct_chos": 48.25,
    "pct_grasas": 35.0,
    "volumen_base_ml": 1000.0,
    "kcal_por_volumen": 1500.0,
    "prote_g_por_volumen": 80.0,
    "chos_g_por_volumen": 180.0,
    "grasa_g_por_volumen": 48.5,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "novasource-proline-sabor-vainilla-nestle",
    "tipo": "ESPECIALES",
    "laboratorio": "NESTLE",
    "nombre": "Novasource proline (Sabor vainilla)",
    "presentacion": "Botella X 200cc (vía oral o sonda)",
    "descripcion_corta": "Fórmula polimérica hiperproteica inmunomodulada (sin selenio, vit A, ACE, Arginina, prolina)",
    "densidad_kcal_ml": 1.35,
    "osmolaridad": 535.0,
    "pct_proteina": 26.0,
    "pct_chos": 25.0,
    "pct_grasas": 49.0,
    "volumen_base_ml": 200.0,
    "kcal_por_volumen": 270.0,
    "prote_g_por_volumen": 17.8,
    "chos_g_por_volumen": 32.0,
    "grasa_g_por_volumen": 7.4,
    "fibra_g_por_volumen": 0.8,
    "grupo_etareo": "",
    "nota": "Fórmula líquida, normocalórica, polimérica, hiperproteica a base de proteína de caseinato de calcio obtenida de la leche de vaca, proteína de soja, larginina, l-prolina, maltodextrina, almidón de tapioca, aceite de canola y soya y aceite de coco y/o palmiste, vitaminas y minerales, para adultos que requieren nutrición oral o por sonda, en situaciones de regeneración de tejidos y cicatrización en heridas de difícil cicatrización incluyendo úlceras por presión en las etapas iii y iv y heridas crónicas de difícil recuperación, que no logran suplir sus requerimientos nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "nutren-pulmonary-nestle",
    "tipo": "ESPECIALES",
    "laboratorio": "NESTLE",
    "nombre": "Nutren pulmonary",
    "presentacion": "Tetraprisma X 250 cc",
    "descripcion_corta": "Fórmula polimérica hipercalórica, baja en carbohidratos con antioxidantes",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 450.0,
    "pct_proteina": 18.0,
    "pct_chos": 25.0,
    "pct_grasas": 57.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 750.0,
    "prote_g_por_volumen": 34.0,
    "chos_g_por_volumen": 50.0,
    "grasa_g_por_volumen": 47.4,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "pulmocare-abbott",
    "tipo": "ESPECIALES",
    "laboratorio": "ABBOTT",
    "nombre": "Pulmocare",
    "presentacion": "Lata X 237 cc",
    "descripcion_corta": "Fórmula polimérica hipercalórica baja en carbohidratos con antioxidantes",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 372.0,
    "pct_proteina": 16.7,
    "pct_chos": 28.2,
    "pct_grasas": 55.1,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 750.0,
    "prote_g_por_volumen": 31.2,
    "chos_g_por_volumen": 52.7,
    "grasa_g_por_volumen": 46.6,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "nutrison-protein-intense-nutricia",
    "tipo": "ESPECIALES",
    "laboratorio": "NUTRICIA",
    "nombre": "Nutrison protein intense",
    "presentacion": "Botella optri X 500 cc administración por sonda sistema prellenado",
    "descripcion_corta": "Fórmula polimérica normocalórica, hiperproteica, baja en carbohidratos",
    "densidad_kcal_ml": 1.26,
    "osmolaridad": 275.0,
    "pct_proteina": 32.0,
    "pct_chos": 32.7,
    "pct_grasas": 35.3,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 630.0,
    "prote_g_por_volumen": 50.0,
    "chos_g_por_volumen": 52.0,
    "grasa_g_por_volumen": 24.5,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "de niños a partir de 12 años, adultos y adultos mayores",
    "nota": "Hiperproteica, normocalórica, líquida, lista para usar, sin lactosa, con proteínas (de suero, caseína, soya, arveja), carbohidratos, grasas, triglicéridos de cadena media - tcm, ácidos grasos poliinsaturados esenciales – e-pufas, vitaminas, minerales, oligoelementos y carotenoides, para el manejo nutricional enteral por sonda a mediano y largo plazo  en estado crítico, que cursan con, desnutrición proteico calórica secundaria moderada o severa, asociada a enfermedad pulmonar obstructiva crónica (epoc), insuficiencia cardiaca, estado posquirúrgico, trauma, sepsis, quemaduras a partir de grado ii, falla renal en etapa 5, y que no pueden suplir sus necesidades nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "diben-fresenius-kabi",
    "tipo": "ESPECIALES",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Diben",
    "presentacion": "Easy bag X 500",
    "descripcion_corta": "Formula polimérica baja en carbohidratos con fibra",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 270.0,
    "pct_proteina": 17.0,
    "pct_chos": 35.0,
    "pct_grasas": 43.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 22.5,
    "chos_g_por_volumen": 46.25,
    "grasa_g_por_volumen": 25.0,
    "fibra_g_por_volumen": 12.0,
    "grupo_etareo": "Personas a partir de los 3 años de edad",
    "nota": "Para el manejo nutricional de personas a partir de 3 años de edad en estado crítico con hiperglicemia por estrés metabólico (truma, sepsis, procesos infecciosos), desnutrición proteico calórica (moderada o severa) e hiperglicemia por estrés metabólico o diabetes y desnutrición proteico calórica (moderada o severa) asociadas a: Pancreatitis aguda o crónica, cáncer en estadíos III y IV (páncreas, leucemia, linfomas) con incapacidad para suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "glucerna-abbott",
    "tipo": "ESPECIALES",
    "laboratorio": "ABBOTT",
    "nombre": "Glucerna",
    "presentacion": "LPC x 1500 cc",
    "descripcion_corta": "Fórmula polimérica normocalórica baja en carbohidratos (con fibra)",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 328.0,
    "pct_proteina": 16.7,
    "pct_chos": 28.54,
    "pct_grasas": 49.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 20.9,
    "chos_g_por_volumen": 47.7,
    "grasa_g_por_volumen": 27.2,
    "fibra_g_por_volumen": 7.2,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "diben-1-5-hp-fresenius-kabi",
    "tipo": "ESPECIALES",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Diben 1,5 HP",
    "presentacion": "Easy bag X 1000",
    "descripcion_corta": "Fórmula polimérica, baja en carbohidratos, con fibra, alta densidad calórica",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 450.0,
    "pct_proteina": 20.0,
    "pct_chos": 35.0,
    "pct_grasas": 42.0,
    "volumen_base_ml": 1000.0,
    "kcal_por_volumen": 1500.0,
    "prote_g_por_volumen": 75.0,
    "chos_g_por_volumen": 131.0,
    "grasa_g_por_volumen": 70.0,
    "fibra_g_por_volumen": 23.0,
    "grupo_etareo": "Personas a partir de los 3 años de edad",
    "nota": "Para el manejo nutricional de personas con diabetes mellitus asociada a desnutrición proteico-calórica, desnutrición proteíco-calórica con hiperglicemia inducida por estrés con incapacidad para suplir sus requerimientos nutricionales con una alimentación normal o modificada, con requerimientos nutricionales aumentados y/o restricción hídrica."
  },
  {
    "id": "glucerna-1-5-abbott",
    "tipo": "ESPECIALES",
    "laboratorio": "ABBOTT",
    "nombre": "Glucerna 1,5",
    "presentacion": "LPC x 1000 cc",
    "descripcion_corta": "Fórmula hipercalórica, normocalórica, baja en carbohidratos",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 686.0,
    "pct_proteina": 22.0,
    "pct_chos": 28.0,
    "pct_grasas": 45.0,
    "volumen_base_ml": 1000.0,
    "kcal_por_volumen": 1500.0,
    "prote_g_por_volumen": 82.5,
    "chos_g_por_volumen": 105.0,
    "grasa_g_por_volumen": 75.0,
    "fibra_g_por_volumen": 6.0,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "nutrison-diason-energy-hp-nutricia",
    "tipo": "ESPECIALES",
    "laboratorio": "NUTRICIA",
    "nombre": "Nutrison Diason Energy HP",
    "presentacion": "Botella optri X 1000 cc",
    "descripcion_corta": "Fórmula polimérica hipercalórica, baja en chos y con fibra",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 395.0,
    "pct_proteina": 20.5,
    "pct_chos": 31.0,
    "pct_grasas": 46.9,
    "volumen_base_ml": 1000.0,
    "kcal_por_volumen": 1500.0,
    "prote_g_por_volumen": 76.9,
    "chos_g_por_volumen": 117.0,
    "grasa_g_por_volumen": 77.2,
    "fibra_g_por_volumen": 10.0,
    "grupo_etareo": "niños a partir de 12 años, adultos y adultos mayores",
    "nota": "Apme fórmula polimérica, hipercalórica, hiperproteica, líquida, lista para usar, con fibras dietarias, lípidos, ácidos grasos monoinsaturados (mufas) vitaminas, minerales, oligoelementos y  carotenoides. Para el manejo nutricional enteral por sonda o acceso enteral, de con desnutrición proteico-calórica secundaria moderada o severa, disfagia moderada o severa, insuficiencia respiratoria aguda, insuficiencia cardiaca, estado posquirúrgico, trauma, sepsis, o falla renal en etapa 5, con diabetes mellitus o estados de hiperglicemia, que no pueden suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "nepro-bp-abbott",
    "tipo": "ESPECIALES",
    "laboratorio": "ABBOTT",
    "nombre": "Nepro BP",
    "presentacion": "Lata X 237 cc",
    "descripcion_corta": "Fórmula polimérica baja en proteínas , fósforo y potasio",
    "densidad_kcal_ml": 1.8,
    "osmolaridad": 566.0,
    "pct_proteina": 10.0,
    "pct_chos": 41.0,
    "pct_grasas": 48.0,
    "volumen_base_ml": 237.0,
    "kcal_por_volumen": 427.0,
    "prote_g_por_volumen": 10.6,
    "chos_g_por_volumen": 46.4,
    "grasa_g_por_volumen": 22.7,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "Adolescentes y adultos con enfermedad renal en estadios 3 a 5",
    "nota": "Alimento para propósitos médicos especiales líquido, a base de maltodextrina de maíz, hipercalórico, para adolescentes y adultos con desnutrición proteico-calórica moderada o severa o con desgaste proteico-energético y enfermedad renal en estadio 2;  (pre-diálisis) que por su condición médica no logran suplir sus requerimientos nutricionales o metabólicos con una alimentación normal o modificada"
  },
  {
    "id": "fresubin-renal-fresenius-kabi",
    "tipo": "ESPECIALES",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Fresubin renal",
    "presentacion": "Botella X 200cc",
    "descripcion_corta": "Fórmula polimérica baja en proteínas , fósforo y potasio",
    "densidad_kcal_ml": 2.0,
    "osmolaridad": 500.0,
    "pct_proteina": 6.0,
    "pct_chos": 53.0,
    "pct_grasas": 40.0,
    "volumen_base_ml": 237.0,
    "kcal_por_volumen": 474.0,
    "prote_g_por_volumen": 7.1,
    "chos_g_por_volumen": 62.5,
    "grasa_g_por_volumen": 21.1,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "Personas a partir de los 3 años de edad",
    "nota": "Para el manejo nutricional de personas a partir de los 3 años de edad, con insuficiencia renal aguda o crónica en estadio 2, 3 y 4 con desnutrición proteicocalórica que no puedan suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "nepro-ap-abbott",
    "tipo": "ESPECIALES",
    "laboratorio": "ABBOTT",
    "nombre": "Nepro AP",
    "presentacion": "Lata X 237 cc",
    "descripcion_corta": "Fórmula polimérica alta en proteínas, baja en fósforo y potasio , alta densidad calórica",
    "densidad_kcal_ml": 1.8,
    "osmolaridad": 540.0,
    "pct_proteina": 18.0,
    "pct_chos": 33.0,
    "pct_grasas": 48.0,
    "volumen_base_ml": 237.0,
    "kcal_por_volumen": 427.0,
    "prote_g_por_volumen": 19.1,
    "chos_g_por_volumen": 37.9,
    "grasa_g_por_volumen": 22.7,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "Adolescentes y adultos",
    "nota": "Alimento para propósitos médicos especiales líquido, a base de jarabe de sólidos de maíz y caseinatos, hipercalórico, para con enfermedad renal aguda o crónica en estadio 5 (diálisis) que por su condición médica no logran suplir sus requerimientos nutricionales o metabólicos con una alimentación normal o modificada"
  },
  {
    "id": "supportan-drink-fresenius-kabi",
    "tipo": "ESPECIALES",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Supportan drink",
    "presentacion": "Botella X 200cc",
    "descripcion_corta": "Fórmula polimérica, alta en proteinas y densidad calórica, tiene TCM, EPA , DHA",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": null,
    "pct_proteina": 27.0,
    "pct_chos": 31.0,
    "pct_grasas": 40.0,
    "volumen_base_ml": 220.0,
    "kcal_por_volumen": 330.0,
    "prote_g_por_volumen": 22.0,
    "chos_g_por_volumen": 25.5,
    "grasa_g_por_volumen": 14.7,
    "fibra_g_por_volumen": 3.3,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "prosure-abbott",
    "tipo": "ESPECIALES",
    "laboratorio": "ABBOTT",
    "nombre": "Prosure",
    "presentacion": "Botella x 220",
    "descripcion_corta": "Fórmula polimérica hiperproteica, con EPA, FOS",
    "densidad_kcal_ml": 1.27,
    "osmolaridad": 597.0,
    "pct_proteina": 21.0,
    "pct_chos": 57.8,
    "pct_grasas": 17.96,
    "volumen_base_ml": 220.0,
    "kcal_por_volumen": 279.0,
    "prote_g_por_volumen": 14.63,
    "chos_g_por_volumen": 40.33,
    "grasa_g_por_volumen": 5.56,
    "fibra_g_por_volumen": 4.55,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "fortisip-compact-protein-nutricia",
    "tipo": "ESPECIALES",
    "laboratorio": "NUTRICIA",
    "nombre": "Fortisip compact protein",
    "presentacion": "Botella x 125 (Frutos rojos, tropical, neutro)",
    "descripcion_corta": "Fórmula polimérica hiperproteica, alta densidad calórica",
    "densidad_kcal_ml": 2.45,
    "osmolaridad": 570.0,
    "pct_proteina": 23.8,
    "pct_chos": 41.2,
    "pct_grasas": 35.0,
    "volumen_base_ml": 125.0,
    "kcal_por_volumen": 306.0,
    "prote_g_por_volumen": 18.25,
    "chos_g_por_volumen": 31.63,
    "grasa_g_por_volumen": 12.0,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "niños mayores de 6 años y adultos",
    "nota": "Alimento para propósitos médicos especiales. Fórmula polimérica, lista para consumir, líquida, de volumen reducido, hipercalórica, alta en proteína láctea, con carbohidratos, grasas, vitaminas, minerales, ácidos grasos esenciales (linoleico y alfa-linolénico) y colina. Para alimentación por vía oral en  con requerimientos nutricionales incrementados en desnutrición proteicocalórica, durante estados pre y postoperatorios, situaciones de regeneración y cicatrización de tejidos en quemaduras a partir de grado 2, sida, cáncer en tratamiento con quimioterapia y radioterapia, sarcopenia, caquexia secundaria a enfermedades catabólicas, que no puedan suplir sus requerimientos nutricionales con una alimentación convencional"
  },
  {
    "id": "fresubin-hepa-drink-fresenius-kabi",
    "tipo": "ESPECIALES",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Fresubin Hepa drink",
    "presentacion": "Botella X 200cc (sabor capuchino)",
    "descripcion_corta": "Fórmula polimérica, alta densidad calórica, mayor contenido de aa de cadena ramificada",
    "densidad_kcal_ml": 1.3,
    "osmolaridad": 360.0,
    "pct_proteina": 12.3,
    "pct_chos": 53.8,
    "pct_grasas": 31.17,
    "volumen_base_ml": 200.0,
    "kcal_por_volumen": 260.0,
    "prote_g_por_volumen": 8.0,
    "chos_g_por_volumen": 35.0,
    "grasa_g_por_volumen": 9.0,
    "fibra_g_por_volumen": 2.0,
    "grupo_etareo": "Personas a partir de los 3 años de edad",
    "nota": "Para el manejo nutricional de personas a partir de 3 años de edad, con insuficiencia hepática y/o encefalopatía hepática, con desnutrición proteicocalórica con incapacidad para suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "p-ptamen-prebio-1-nestle",
    "tipo": "OLIGOMÉRICOS",
    "laboratorio": "NESTLE",
    "nombre": "Péptamen prebio 1",
    "presentacion": "Tetraprisma X 250 cc",
    "descripcion_corta": "Fórmula oligomérica con péptidos",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 300.0,
    "pct_proteina": 16.0,
    "pct_chos": 48.0,
    "pct_grasas": 36.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 20.0,
    "chos_g_por_volumen": 64.0,
    "grasa_g_por_volumen": 20.0,
    "fibra_g_por_volumen": 1.0,
    "grupo_etareo": "niños mayores de 14 años y adultos",
    "nota": "Oligomérico, líquido, normoproteico, normocalórico, a base de maltodextrina y proteína hidrolizada del suero de la leche, con lípidos, vitaminas, minerales y fibras (inulina y fos), para pacientes con desnutrición proteico calórica moderada asociada a malabsorción intestinal, pancreatitis aguda, enfermedad de crohn; enfermedades desgastantes (estado crítico, sida, parálisis cerebral, fibrosis quística), que no logran suplir sus requerimientos nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "nutrison-advance-peptisorb-nutricia",
    "tipo": "OLIGOMÉRICOS",
    "laboratorio": "NUTRICIA",
    "nombre": "Nutrison advance Peptisorb",
    "presentacion": "Botella optri X 500 cc",
    "descripcion_corta": "Fórmula oligomérica hidrolizado de proteína de suero TCM",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 455.0,
    "pct_proteina": 15.7,
    "pct_chos": 69.2,
    "pct_grasas": 15.1,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 500.0,
    "prote_g_por_volumen": 20.0,
    "chos_g_por_volumen": 88.5,
    "grasa_g_por_volumen": 8.5,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "survimed-opd-hn-fresenius-kabi",
    "tipo": "OLIGOMÉRICOS",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Survimed OPD HN",
    "presentacion": "Easy bag x 500cc",
    "descripcion_corta": "Fórmula oligomérica con péptidos, alta densidad calórica",
    "densidad_kcal_ml": 1.33,
    "osmolaridad": 370.0,
    "pct_proteina": 20.0,
    "pct_chos": 55.0,
    "pct_grasas": 25.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 665.0,
    "prote_g_por_volumen": 33.5,
    "chos_g_por_volumen": 91.5,
    "grasa_g_por_volumen": 18.5,
    "fibra_g_por_volumen": 23.0,
    "grupo_etareo": "Personas a partir de los 3 años de edad",
    "nota": "Para el manejo nutricional de personas a partir de 3 años, con desnutrición proteico-calórica moderada o severa asociada a: Enfermedad de crohn, síndrome de malabsorción intestinal, pancreatitis, enteritis por radiación o quimioterapia, síndrome de intestino corto, con incapacidad para suplir sus requerimientos con una alimentación normal o modificada, con requerimiento energéticos y proteicos elevados."
  },
  {
    "id": "perative-lpc-abbott",
    "tipo": "OLIGOMÉRICOS",
    "laboratorio": "ABBOTT",
    "nombre": "Perative LPC",
    "presentacion": "LPC 1000 cc",
    "descripcion_corta": "Fórmula oligomérica con péptidos",
    "densidad_kcal_ml": 1.3,
    "osmolaridad": 304.0,
    "pct_proteina": 20.5,
    "pct_chos": 54.0,
    "pct_grasas": 25.0,
    "volumen_base_ml": 500.0,
    "kcal_por_volumen": 650.0,
    "prote_g_por_volumen": 33.3,
    "chos_g_por_volumen": 88.5,
    "grasa_g_por_volumen": 18.7,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "vital-1-5-abbott",
    "tipo": "OLIGOMÉRICOS",
    "laboratorio": "ABBOTT",
    "nombre": "Vital 1,5",
    "presentacion": "Botella x 220 (Vía oral)",
    "descripcion_corta": "Fórmula oligomérica con péptidos, alta densidad calórica",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 487.0,
    "pct_proteina": 18.32,
    "pct_chos": 49.93,
    "pct_grasas": 31.75,
    "volumen_base_ml": 220.0,
    "kcal_por_volumen": 330.0,
    "prote_g_por_volumen": 14.85,
    "chos_g_por_volumen": 40.48,
    "grasa_g_por_volumen": 12.1,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "Adultos",
    "nota": "Oligomérico, hipercalórico, a base de maltodextrina, proteína hidrolizada y triglicéridos de cadena media (tcm) con desnutrición proteico-calórica moderada o severa que presentan problemas de malabsorción intestinal asociados con fibrosis quística, insuficiencia pancreática, enfermedad de crohn, colitis ulcerativa, síndrome de intestino corto, enterocolitis y sepsis, que no logran suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "ensure-abbott",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "ABBOTT",
    "nombre": "Ensure",
    "presentacion": "Frasco 220 ml",
    "descripcion_corta": "Fórmula polimérica para adultos",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 418.0,
    "pct_proteina": 14.2,
    "pct_chos": 61.8,
    "pct_grasas": 21.5,
    "volumen_base_ml": 220.0,
    "kcal_por_volumen": 234.0,
    "prote_g_por_volumen": 8.36,
    "chos_g_por_volumen": 36.21,
    "grasa_g_por_volumen": 5.59,
    "fibra_g_por_volumen": 2.79,
    "grupo_etareo": "Adulto",
    "nota": "Polimérico, a base de almidón de maíz hidrolizado, para alimentación por vía oral o sonda, dirigido a adultos con desnutrición proteico-calórica moderada asociada a: vih/sida, pre y post operatorios de cirugía mayor, cáncer en estadios iii y iv (colorrectal, mama, esófago, estómago, pulmón, cabeza y cuello, cuello uterino, ovario) y enfermedades neurológicas (alzheimer, lesión postraumática cráneoencefálica, lesión axonal, secuelas de acv, ela), que no logran suplir sus requerimientos nutricionales con una alimentación normal o modificada. Sabores vainilla, fresa"
  },
  {
    "id": "pediasure-abbott",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "ABBOTT",
    "nombre": "Pediasure",
    "presentacion": "Botella X 220 ml (Vainilla y fresa)",
    "descripcion_corta": "Fórmula polimérica para niños 2-13 años",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 343.0,
    "pct_proteina": 12.0,
    "pct_chos": 55.1,
    "pct_grasas": 34.5,
    "volumen_base_ml": 220.0,
    "kcal_por_volumen": 221.0,
    "prote_g_por_volumen": 6.6,
    "chos_g_por_volumen": 30.47,
    "grasa_g_por_volumen": 8.47,
    "fibra_g_por_volumen": 1.54,
    "grupo_etareo": "Niños de 2 a 13 años",
    "nota": "Alimento para propósitos médicos especiales en polvo, polimérico, a base de maltodextrina, proteína (concentrado de proteína de leche, aislado de proteína de soya), lípidos, vitaminas y minerales, para el manejo nutricional de , por vía oral o sonda, con desnutrición proteico - calórica moderada asociada a: enfermedad cardíaca congénita, enfermedades neurológicas (parálisis cerebral, secuelas de traumatismos de la cabeza, duchenne, microcefalia), leucemia, fibrosis quística, estados pre y posquirúrgicos de cirugía mayor, sepsis, enfermedad inflamatoria intestinal, distrofia muscular, que no pueden suplir sus requerimientos nutricionales con una alimentación normal o modificada. Variedad 1: sin fosfopéptidos de caseína. Sabores vainilla, fresa, chocolate. Variedad 2: con fosfopéptidos de caseína. Sabores vainilla, fresa, chocolate"
  },
  {
    "id": "infatrini-nutricia",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "NUTRICIA",
    "nombre": "Infatrini",
    "presentacion": "Botella X 125 ml / Lata x 400 gr",
    "descripcion_corta": "Fórmula polimérica de normocalórica 0-18 meses (o 9 kilogramos) con  FOS y GOS",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 305.0,
    "pct_proteina": 10.2,
    "pct_chos": 41.7,
    "pct_grasas": 48.1,
    "volumen_base_ml": 125.0,
    "kcal_por_volumen": 125.0,
    "prote_g_por_volumen": 3.3,
    "chos_g_por_volumen": 12.8,
    "grasa_g_por_volumen": 6.6,
    "fibra_g_por_volumen": 0.7,
    "grupo_etareo": "niños de 0-18 meses (o hasta 9 k de peso)",
    "nota": "Fórmula polimérica, líquida, lista para consumir, normocalórica, láctea, con carbohidratos, rasas, proteínas, fibra dietaria (GOS+FOS), vitaminas, minerales, oli oelementos, nucleótidos, tri licéridos de cadena media TCM y ácidos rasos poliinsaturados de cadena lar a (DHA, EPA Y AA). Para alimentación por vía enteral (oral o sonda) en  con requerimientos ener éticos incrementados por desnutrición secundaria a cardiopatías conénitas (malformaciones conénitas), displasia broncopulmonar, sida, parálisis cerebral, neoplasias mali nas, estado crítico secundario a bronquiolitis auda, que no pueden suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "frebini-energy-fibre-fresenius-kabi",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "FRESENIUS KABI",
    "nombre": "Frebini energy fibre",
    "presentacion": "Botella x 200 ml",
    "descripcion_corta": "Fórmula prolimérica de alta densidad calórica para niños de 1 a 12 años",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 400.0,
    "pct_proteina": 10.2,
    "pct_chos": 48.3,
    "pct_grasas": 40.0,
    "volumen_base_ml": 200.0,
    "kcal_por_volumen": 300.0,
    "prote_g_por_volumen": 7.6,
    "chos_g_por_volumen": 36.2,
    "grasa_g_por_volumen": 13.4,
    "fibra_g_por_volumen": 2.2,
    "grupo_etareo": "Personas de 1 a 12 años",
    "nota": "Fórmula polimérica, para alimentación por sonda, hipercalórica 1.5 kcal/ml, normoprotéica. A base de maltodextrina, lípidos y proteína láctea (caseina y proteína whey). Contiene taurina, carnitina e inositol, fibra soluble, vitaminas y minerales. Para el manejo nutricional de , con retardo del desarrollo con o sin desnutrición proteicocalórica, retraso mental, fibrosis quística, enfermedad de crohn, enfermedad celiaca y cáncer del tracto gastrointestinal con incapacidad para suplir sus requerimientos nutricionales con una alimentación normal o modificada"
  },
  {
    "id": "pediasure-clinical-abbott",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "ABBOTT",
    "nombre": "Pediasure clinical",
    "presentacion": "Botella X 220 ml",
    "descripcion_corta": "Fórmula polimérica de alta densidad calórica para niños de 1- 13 años",
    "densidad_kcal_ml": 1.5,
    "osmolaridad": 388.0,
    "pct_proteina": 11.2,
    "pct_chos": 43.7,
    "pct_grasas": 44.8,
    "volumen_base_ml": 220.0,
    "kcal_por_volumen": 330.0,
    "prote_g_por_volumen": 9.24,
    "chos_g_por_volumen": 36.06,
    "grasa_g_por_volumen": 6.43,
    "fibra_g_por_volumen": 2.42,
    "grupo_etareo": "niños de 1 a 13 años",
    "nota": "Polimérico, para alimentación por vía oral o sonda, hipercalórico, a base de maltodextrina, lípidos, mezcla de proteína (caseinato, concentrado de suero), con fibra, para el manejo nutricional, anorexia, retraso en el desarrollo con o sin desnutrición proteico calórica, preparación preoperatoria de pacientes malnutridos y recuperación post- operatoria, con o en riesgo de desnutrición asociada a: episodios repetidos de infecciones respiratorias, infección por vih, enfermedad de crohn, fibrosis quística, enfermedad cardiaca congénita, enfermedad neurológica, enfermedad oncológica, que no puede suplir sus requerimientos nutricionales con una alimentación normal o modificada."
  },
  {
    "id": "p-ptamen-junior-nestl",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "NESTLÉ",
    "nombre": "Péptamen Junior",
    "presentacion": "Tetraprisma X 250 cc",
    "descripcion_corta": "Fórmula oligomérica con péptidos normocalórica para niños de 1 - 13 años",
    "densidad_kcal_ml": 1.08,
    "osmolaridad": 380.0,
    "pct_proteina": 12.0,
    "pct_chos": 54.0,
    "pct_grasas": 34.0,
    "volumen_base_ml": 250.0,
    "kcal_por_volumen": 270.0,
    "prote_g_por_volumen": 8.0,
    "chos_g_por_volumen": 36.0,
    "grasa_g_por_volumen": 10.0,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "niños de 1 a 13 años",
    "nota": "Fórmula oligomérica, normocalórica, a base de maltodextrina, proteína concentrada de suero de leche hidrolizada, triglicéridos de cadena media, almidón de maíz, aceite de soya, aceite de colza, vitaminas y minerales, para manejo nutricional con desnutrición proteico calorica de grado moderado o severo debido a: parálisis cerebral, fibrosis quistica, enfermedad de crohn, traumatismos múltiples y sepsis grave, que no logran suplir sus requerimientos nutricionales y/o metabólicos con una alimentación normal o modificada"
  },
  {
    "id": "kindergen-nutricia",
    "tipo": "FÓRMULAS PEDIÁTRICAS",
    "laboratorio": "NUTRICIA",
    "nombre": "Kindergen",
    "presentacion": "Lata X 400 gr",
    "descripcion_corta": "Fórmula especial para niños con insuficiencia renal crónica 0-3 años",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 235.0,
    "pct_proteina": 6.0,
    "pct_chos": 46.1,
    "pct_grasas": 46.8,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 100.0,
    "prote_g_por_volumen": 1.5,
    "chos_g_por_volumen": 11.6,
    "grasa_g_por_volumen": 5.2,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "en niños desde 0 hasta 5 años",
    "nota": "Fórmula para enfermedades específicas, en polvo, con proteína de suero de leche, carbohidratos, fibra dietaria (fos+gos), grasas, ácidos grasos (linoleico, alfa-linolénico, araquidónico, epa, dha), vitaminas, minerales y oligoelementos, con niveles modificados de potasio, fósforo, cloruro, calcio y vitamina a. Para el manejo nutricional enteral, vía oral o sonda, en niños desde 0 hasta 5 años con enfermedad renal crónica (insuficiencia renal crónica), incluyendo aquellos que requieren diálisis peritoneal o que cursan con desnutrición secundaria a esta condición y que no pueden suplir sus requerimientos nutricionales con una alimentación convencional."
  },
  {
    "id": "similac-hmo-abbott",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "ABBOTT",
    "nombre": "Similac HMO",
    "presentacion": "Botella plástica x 59 ml",
    "descripcion_corta": "Fórmula infantil para lactantes de 0-6 meses",
    "densidad_kcal_ml": 0.6,
    "osmolaridad": null,
    "pct_proteina": 8.2,
    "pct_chos": 43.2,
    "pct_grasas": 49.3,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 64.3,
    "prote_g_por_volumen": 1.32,
    "chos_g_por_volumen": 6.92,
    "grasa_g_por_volumen": 3.52,
    "fibra_g_por_volumen": 20.2,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "especial-care-abbott",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "ABBOTT",
    "nombre": "Especial care",
    "presentacion": "Botella plástica x 59 ml",
    "descripcion_corta": "Fórmula líquida para lactantes prematuros y/o bajo peso al nacer",
    "densidad_kcal_ml": 0.8,
    "osmolaridad": null,
    "pct_proteina": 11.8,
    "pct_chos": 49.0,
    "pct_grasas": 41.5,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 81.0,
    "prote_g_por_volumen": 2.4,
    "chos_g_por_volumen": 8.4,
    "grasa_g_por_volumen": 4.41,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "similac-total-confort-abbott",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "ABBOTT",
    "nombre": "Similac total confort",
    "presentacion": "Lata x 360 gr",
    "descripcion_corta": "Fórmula infantil en polvo baja en lactosa, proteína parcialmente hidrolizada para lactante de 0 a 12 meses",
    "densidad_kcal_ml": 0.67,
    "osmolaridad": null,
    "pct_proteina": 9.2,
    "pct_chos": 42.6,
    "pct_grasas": 48.4,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 68.0,
    "prote_g_por_volumen": 1.56,
    "chos_g_por_volumen": 7.25,
    "grasa_g_por_volumen": 3.66,
    "fibra_g_por_volumen": 0.4,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "nutrilon-pepti-junior-nutricia",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "NUTRICIA",
    "nombre": "Nutrilon pepti junior",
    "presentacion": "Lata X 400 gr",
    "descripcion_corta": "Fórmula oligomérica con proteína de suero extensamente hidrolizada",
    "densidad_kcal_ml": 0.67,
    "osmolaridad": 190.0,
    "pct_proteina": 11.0,
    "pct_chos": 41.2,
    "pct_grasas": 48.0,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 66.0,
    "prote_g_por_volumen": 1.8,
    "chos_g_por_volumen": 6.8,
    "grasa_g_por_volumen": 3.5,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "nutramigen-lgg-mead-jhonson",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "MEAD JHONSON",
    "nombre": "Nutramigen LGG",
    "presentacion": "Lata X 357 gr",
    "descripcion_corta": "Fórmula oligomérica con proteína extensamente hidrolizada y probióticos, sin lactosa. Para niños de 0 a 12 meses",
    "densidad_kcal_ml": 0.8,
    "osmolaridad": null,
    "pct_proteina": 11.2,
    "pct_chos": 41.7,
    "pct_grasas": 46.3,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 68.0,
    "prote_g_por_volumen": 1.9,
    "chos_g_por_volumen": 7.1,
    "grasa_g_por_volumen": 3.5,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "neocate-syneo-nutricia",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "NUTRICIA",
    "nombre": "Neocate SYNEO",
    "presentacion": "Lata X 400 gr",
    "descripcion_corta": "Fórmula monomérica con simbióticos de 0-12 meses",
    "densidad_kcal_ml": 0.67,
    "osmolaridad": 310.0,
    "pct_proteina": 11.6,
    "pct_chos": 44.4,
    "pct_grasas": 44.0,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 66.0,
    "prote_g_por_volumen": 1.9,
    "chos_g_por_volumen": 8.13,
    "grasa_g_por_volumen": 3.2,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "neocate-junior-nutricia",
    "tipo": "FÓRMULA INFANTILES",
    "laboratorio": "NUTRICIA",
    "nombre": "Neocate Junior",
    "presentacion": "Lata X 400 gr",
    "descripcion_corta": "Fórmula monomérica sin lactosa con aminoácidos libres, TCM, FOS, niños de 1 a 10 años",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 520.0,
    "pct_proteina": 12.4,
    "pct_chos": 43.6,
    "pct_grasas": 44.1,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 100.0,
    "prote_g_por_volumen": 3.1,
    "chos_g_por_volumen": 10.9,
    "grasa_g_por_volumen": 4.9,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "ensure-advance-abbott",
    "tipo": "FÓRMULAS PARA RECONSTITUCIÓN- SERVICIO DE ALIMENTOS",
    "laboratorio": "ABBOTT",
    "nombre": "Ensure advance",
    "presentacion": "Lata X 400 gr (Sabor vainilla)",
    "descripcion_corta": "Fórmula polimérica, con HMB, distribución estándar",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 474.0,
    "pct_proteina": 14.93,
    "pct_chos": 52.46,
    "pct_grasas": 29.58,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 100.0,
    "prote_g_por_volumen": 3.74,
    "chos_g_por_volumen": 13.15,
    "grasa_g_por_volumen": 3.3,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "prowhey-net-boydorr",
    "tipo": "FÓRMULAS PARA RECONSTITUCIÓN- SERVICIO DE ALIMENTOS",
    "laboratorio": "BOYDORR",
    "nombre": "Prowhey Net",
    "presentacion": "Lata X 434 gr  (Sabor vainilla)",
    "descripcion_corta": "Fórmula polimérica, distribución estándar",
    "densidad_kcal_ml": 1.02,
    "osmolaridad": 296.0,
    "pct_proteina": 20.0,
    "pct_chos": 45.0,
    "pct_grasas": 35.0,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 103.0,
    "prote_g_por_volumen": 5.25,
    "chos_g_por_volumen": 11.25,
    "grasa_g_por_volumen": 4.04,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "fortimel-advance-nutricia",
    "tipo": "FÓRMULAS PARA RECONSTITUCIÓN- SERVICIO DE ALIMENTOS",
    "laboratorio": "NUTRICIA",
    "nombre": "Fortimel advance",
    "presentacion": "Lata X 380 gr (Sabor fresa)",
    "descripcion_corta": "Fórmula polimérica, hiperproteica FOS y GOS",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 410.0,
    "pct_proteina": 55.0,
    "pct_chos": 25.3,
    "pct_grasas": 18.0,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 100.0,
    "prote_g_por_volumen": 13.8,
    "chos_g_por_volumen": 6.4,
    "grasa_g_por_volumen": 2.0,
    "fibra_g_por_volumen": 1.7,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "glucerna-abbott-2",
    "tipo": "FÓRMULAS PARA RECONSTITUCIÓN- SERVICIO DE ALIMENTOS",
    "laboratorio": "ABBOTT",
    "nombre": "Glucerna",
    "presentacion": "Lata X 400 gr (Sabor vainilla)",
    "descripcion_corta": "Fórmula polimérica, baja en carbohidratos y bajo índice glicemico FOS",
    "densidad_kcal_ml": 0.94,
    "osmolaridad": 490.0,
    "pct_proteina": 17.91,
    "pct_chos": 36.16,
    "pct_grasas": 32.57,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 94.0,
    "prote_g_por_volumen": 4.23,
    "chos_g_por_volumen": 8.54,
    "grasa_g_por_volumen": 3.42,
    "fibra_g_por_volumen": 2.16,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "fortisip-casilan-nutricia",
    "tipo": "FÓRMULAS PARA RECONSTITUCIÓN- SERVICIO DE ALIMENTOS",
    "laboratorio": "NUTRICIA",
    "nombre": "Fortisip casilan",
    "presentacion": "Lata X 225 gr (Sabor vainilla)",
    "descripcion_corta": "Fórmula modular, proteína whey + caseína",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": 25.0,
    "pct_proteina": 95.0,
    "pct_chos": 1.0,
    "pct_grasas": 4.0,
    "volumen_base_ml": null,
    "kcal_por_volumen": null,
    "prote_g_por_volumen": null,
    "chos_g_por_volumen": null,
    "grasa_g_por_volumen": null,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  },
  {
    "id": "pediasure-abbott-2",
    "tipo": "FÓRMULAS PARA RECONSTITUCIÓN- SERVICIO DE ALIMENTOS",
    "laboratorio": "ABBOTT",
    "nombre": "Pediasure",
    "presentacion": "Lata X 400 gr (Sabor frresa, vainilla)",
    "descripcion_corta": "Fórmula polimérica normocalórica",
    "densidad_kcal_ml": 1.0,
    "osmolaridad": null,
    "pct_proteina": 12.01,
    "pct_chos": 43.76,
    "pct_grasas": 44.23,
    "volumen_base_ml": 100.0,
    "kcal_por_volumen": 100.0,
    "prote_g_por_volumen": 3.0,
    "chos_g_por_volumen": 1.95,
    "grasa_g_por_volumen": 4.98,
    "fibra_g_por_volumen": null,
    "grupo_etareo": "",
    "nota": ""
  }
];
